name: Continuous Integration
on: [push]

jobs:
  init:
    name: Init
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Print Hello World
        run: echo "Hello World"
  build:
    name: Build and test C# code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x.x'
      - name: build C#
        run: dotnet build
      - name: run C# tests
        run: dotnet test
