name: Continuous Integration
on: [push]

jobs:
  init:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Print Hello World
        run: echo "Hello World"
  build:
    name: Build and test C# code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Step 1
        run: echo "hello"
      - name: Step 2
        run: echo "World"
